{% set name = "azure-mgmt-datafactory" %}
{% set version = "9.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/azure-mgmt-datafactory-{{ version }}.tar.gz
  sha256: 8f54cc7b6fe391255aee9e00afd1e6663879e8636ab641cff906d2bb24c34f4e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - isodate >=0.6.1
    - azure-common >=1.1
    - azure-mgmt-core >=1.3.2
    - typing-extensions >=4.6.0

test:
  imports:
    - azure.mgmt.datafactory
    - azure.mgmt.datafactory.aio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python
  summary: Microsoft Azure Data Factory Management Client Library for Python
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - xylar
