{% set name = "azure-mgmt-datafactory" %}
{% set version = "7.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/azure-mgmt-datafactory-{{ version }}.tar.gz
  sha256: f7dbafc8fc33467531a7878f0395dad7d4154d1be4023bc70d520681b7013fba

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
  run:
    # bumping python constraint 3.8 so we don't need typing-extensions
    - python >=3.8
    - isodate >=0.6.1
    - azure-common >=1.1
    - azure-mgmt-core >=1.3.2

test:
  imports:
    - azure.mgmt.datafactory
    - azure.mgmt.datafactory.aio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python
  summary: Microsoft Azure Data Factory Management Client Library for Python
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - xylar
